name: Build Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          $pyinstallerCmd = @(
            "pyinstaller",
            "--onefile",
            "--name=playlist-downloader",
            "--hidden-import=yt_dlp",
            "--hidden-import=ffmpeg",
            "--collect-all=yt_dlp",
            "--collect-all=ffmpeg",
            "--add-data=.;.",
            "playlist_downloader.py"
          ) -join " "
          Invoke-Expression $pyinstallerCmd
          
          mkdir release_assets
          move dist\playlist-downloader.exe release_assets\playlist-downloader-windows.exe
          dir release_assets

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release_assets/playlist-downloader-windows.exe
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO_ACTION }}
