name: Build Linux

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller youtube-dl ffmpeg-python

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --name playlist-downloader playlist_downloader.py
          mkdir -p release_assets
          mv dist/playlist-downloader release_assets/playlist-downloader-linux
          chmod +x release_assets/playlist-downloader-linux

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release_assets/playlist-downloader-linux
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO_ACTION }}
