name: Build Windows and Linux

on:
  push:
    tags:
      - 'v*'  # Dispara quando tags como v1.0.0 são criadas

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller youtube-dl ffmpeg-python

      - name: Build Executable
        run: |
          pyinstaller --onefile playlist_downloader.py
          # Ajusta o nome do executável para Linux
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv dist/playlist_downloader dist/playlist-downloader-linux
          fi
          # O Windows já gera com .exe automaticamente

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/playlist-downloader-linux
            dist/playlist_downloader.exe
          tag_name: ${{ github.ref }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO_ACTION }}
