name: Build Windows and Linux

on:
  push:
    tags:
      - 'v*'  # Dispara quando tags como v1.0.0 são criadas

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: pip install pyinstaller youtube-dl ffmpeg-python

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller youtube-dl ffmpeg-python

      - name: Build Executable
        run: |
          pyinstaller --onefile --name playlist-downloader playlist_downloader.py
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv dist/playlist-downloader dist/playlist-downloader-linux
          else
            mv dist/playlist-downloader.exe dist/playlist-downloader-windows.exe
          fi

      - name: Verify files
        run: |
          echo "Generated files:"
          ls -la dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executables-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: List downloaded files
        run: |
          echo "Artifacts downloaded:"
          find ./artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/executables-ubuntu-latest/playlist-downloader-linux
            artifacts/executables-windows-latest/playlist-downloader-windows.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO_ACTION }}
