name: Build Windows and Linux

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller youtube-dl ffmpeg-python

      - name: Build Executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --name playlist-downloader playlist_downloader.py
          mkdir -p release_assets
          mv dist/playlist-downloader release_assets/playlist-downloader-linux
          chmod +x release_assets/playlist-downloader-linux

      - name: Build Executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --name playlist-downloader playlist_downloader.py
          mkdir release_assets
          move dist\playlist-downloader.exe release_assets\playlist-downloader-windows.exe

      - name: Verify files
        run: |
          echo "Generated files:"
          ls -la release_assets/ || dir release_assets

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: release_assets/
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: combined_artifacts
          pattern: executables-*
          merge-multiple: true

      - name: List files for debug
        run: |
          echo "Files available for release:"
          find combined_artifacts -type f -exec ls -la {} \;

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            combined_artifacts/executables-ubuntu-latest/playlist-downloader-linux
            combined_artifacts/executables-windows-latest/playlist-downloader-windows.exe
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO_ACTION }}
